// Datos curiosos del día. Sin base de datos: se elige uno por fecha de forma
// determinista, así todos ven el mismo dato cada día.
export const FUN_FACTS: string[] = [
  "Los pulpos tienen tres corazones y sangre azul.",
  "La miel nunca se echa a perder: se ha encontrado miel comestible de hace más de 3000 años.",
  "Un rayo puede ser más caliente que la superficie del Sol.",
  "Los flamencos son rosados por lo que comen: camarones y algas.",
  "La Torre Eiffel puede crecer hasta 15 cm en verano por la dilatación del metal.",
  "Los plátanos son, botánicamente, bayas; las frutillas no.",
  "Un día en Venus dura más que un año en Venus.",
  "Las nutrias se toman de las manos al dormir para no separarse.",
  "El ojo humano puede distinguir cerca de 10 millones de colores.",
  "Los tiburones existen desde antes que los árboles.",
  "Hay más estrellas en el universo que granos de arena en todas las playas de la Tierra.",
  "Los koalas tienen huellas dactilares casi idénticas a las humanas.",
  "Saturno es tan poco denso que flotaría en el agua.",
  "El corazón humano late unas 100.000 veces al día.",
  "La jirafa y el humano tienen el mismo número de vértebras en el cuello: siete.",
  "Las abejas pueden reconocer rostros humanos.",
  "El sonido no se propaga en el vacío del espacio.",
  "La Antártida es el desierto más grande del mundo.",
  "Los delfines se ponen 'nombres': usan silbidos únicos para identificarse.",
  "La Luna se aleja de la Tierra unos 3,8 cm cada año.",
  "Los aztecas usaban semillas de cacao como moneda.",
  "Los caracoles pueden dormir durante varios meses seguidos.",
  "El cerebro humano genera suficiente electricidad para encender una ampolleta pequeña.",
  "El monte Everest crece unos pocos milímetros cada año.",
  "Un grupo de flamencos se llama 'flamboyant'.",
  "El idioma con más hablantes nativos en el mundo es el chino mandarín.",
  "Los pingüinos pueden saltar hasta casi dos metros fuera del agua.",
  "El agua caliente puede congelarse más rápido que la fría en ciertas condiciones.",
  "Marte tiene el volcán más alto conocido del sistema solar: el Monte Olimpo.",
  "Una cucharadita de estrella de neutrones pesaría miles de millones de toneladas.",
  "El cerebro humano usa cerca del 20% de la energía de todo el cuerpo.",
  "Un año en Mercurio dura solo 88 días terrestres.",
  "Las medusas existen desde hace más de 500 millones de años.",
  "El guepardo es el animal terrestre más rápido: alcanza unos 110 km/h.",
  "La lengua de un camaleón puede ser más larga que su propio cuerpo.",
  "Los elefantes son los únicos mamíferos que no pueden saltar.",
  "El corazón de una ballena azul es del tamaño de un auto pequeño.",
  "El punto más profundo del océano es la fosa de las Marianas: casi 11 km.",
  "Los gatos pasan cerca del 70% de su vida durmiendo.",
  "El Sol concentra el 99,8% de la masa de todo el sistema solar.",
  "Las huellas dactilares son únicas, incluso entre gemelos idénticos.",
  "Los pingüinos emperador pueden bucear a más de 500 metros de profundidad.",
  "La Vía Láctea contiene cientos de miles de millones de estrellas.",
  "El país de Bután mide su progreso con la 'Felicidad Nacional Bruta'.",
  "La rotación de la Tierra se frena de a poco: los días duran un poquito más cada siglo.",
  "Un colibrí puede batir sus alas más de 50 veces por segundo.",
  "El metal más abundante en la corteza terrestre es el aluminio.",
  "Los árboles se comunican bajo tierra a través de redes de hongos.",
  "La temperatura en la superficie de Venus supera los 450 °C.",
  "El ADN humano comparte cerca del 60% de sus genes con los del plátano.",
];

export function getFactOfDay(date: Date = new Date()): string {
  const start = Date.UTC(date.getUTCFullYear(), 0, 0);
  const today = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
  const dayOfYear = Math.floor((today - start) / 86_400_000);
  return FUN_FACTS[dayOfYear % FUN_FACTS.length];
}
